### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by Kristen-Watkins** [RajLabMSSM/RajLab_website#2]
super minor; under "join us" --> opportunities it says "if you interested" instead of "if you are interested"

**Comment by bschilder** [comment]
Somehow totally missed this issue until now. Thanks!

**Comment by trajnp** [comment]
Please Add Amanda to the website Team page. Thanks 👍

**Comment by bschilder** [comment]
@trajnp For new issues please used the "New issues" button on the upper right. This thread was already closed. Thanks
